blog/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'blog'

urlpatterns = [
    # as_view() : class 뷰를 function 사용될 때 사용된다.
    # path('', PostList.as_view(), name='list'),
    # path('', postList, name='list'),
    # path('', postList, name='list'),
    # re_path(r'^(?P<page_num>[0-9]+)*/{0,1}$', PostList.as_view(), name='list'),
    path('', PostList.as_view(), name='list'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('create/', PostCreate.as_view(), name='create'),
    path('delete/<int:pk>/', PostDelete.as_view(), name='delete'),
    path('update/<int:pk>/', PostUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='detail'),
    path('category/<int:pk>/', CategoryList.as_view(), name='c_list'),
    path('tags/<tag>/', PostTaggedObjectList.as_view(), name='post_taggedlist'),
    # path('tags/', TagList.as_view(), name='tag_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.urls import re_path

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^media(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),  # S3안쓸때
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from tagging.fields import TagField
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True, allow_unicode=True, db_index=True)
    # parent_category = models.ForeignKey("self", on_delete=models.SET_NULL, blank=True, null=True, default=None)

    def __str__(self):  # -> string
        return self.name + str(f'&게시글 수: {Post.objects.all().count()}')


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name='category')
    # author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,  db_constraint=False, related_name='author')
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True, allow_unicode=True, db_index=True)
    text = RichTextUploadingField()
    tag = TagField(blank=True)
    created = models.DateTimeField(auto_now_add=True, null=False)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        # detail/<int:pk>/
        return reverse('blog:detail', args=[self.id])

blog/forms.py
# from django import forms
# from .models import *
#
#
# class PostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         fields = ['category', 'author', 'title','text']

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, View, TemplateView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Post, Category

from django.http import JsonResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404

from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


class PostList(ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = 'post_object_list'
    paginate_by = 2  # 한 페이지당 요수 갯수

    def get_context_data(self, **kwargs):
        context_data = super(PostList, self).get_context_data(**kwargs)
        # context_data['categories'] = Category.objects.filter(parent_category=None)
        context_data['categories'] = Category.objects.all()
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        if 'category_slug' in self.kwargs:
            try:
                category = Category.objects.get(slug=self.kwargs['category_slug'])
                queryset = queryset.filter(category=category)
            except:
                pass
        return queryset

    def dispatch(self, request, *args, **kwargs):
        post_objects = Post.objects.all()
        paginator = Paginator(post_objects, self.paginate_by)
        context_data = {}
        if request.method == 'GET':
            self.page = request.GET.get('page')
            if self.page is None or int(self.page) < 1:
                self.page = 1
            try:
                list_object = paginator.page(self.page)
            except PageNotAnInteger:
                list_object = paginator.page(1)
            except EmptyPage:
                list_object = paginator.page(paginator.num_pages)
            context_data.update(
                {'object_list': list_object})
            return render(request, 'blog/post_list.html', context_data)
        return super(PostList, self).dispatch(request, *args, **kwargs)


"""
setup -> dispatch -> get_object -> get_queryset -> get_context_data -> render_to_response
이를 직접 구현하는 것이 함수형 뷰
"""


class PostUpdate(UpdateView):
    model = Post
    fields = ['category', 'title', 'text']
    template_name = "blog/post_update.html"
    # success_url = '/'
    # create에서 form_valid가 실행되어있기 때문에 overriding이 필요하지 않음


"""
setup -> dispatch -> get -> post -> get_object -> get_context_data -> rendoer_to_response
"""


# start Create
class PostCreate(CreateView):
    model = Post
    fields = ['category', 'author', 'title', 'text']
    # appname/model_form.html (update & create)
    template_name = "blog/post_create.html"

    def form_valid(self, form):
        form.instance.author.username = self.request.user.id
        return super().form_valid(form)


"""
setup -> dispatch -> get -> post -> get_context_data -> rendoer_to_response
"""

from django.urls import reverse_lazy


class PostDelete(DeleteView):
    model = Post
    template_name = "blog/post_delete.html"
    success_url = reverse_lazy('blog:list')  # reverse_lazy(app_name:urls_name)


class PostDetail(DetailView):
    model = Post
    template_name = "blog/post_detail.html"


class CategoryList(ListView):
    model = Category
    template_name = "blog/category_list.html"
    context_object_name = "category_object_list"


class AboutView(TemplateView):
    template_name = "blog/about.html"


from django.core.mail import EmailMessage
from django.conf import settings


class ContactView(TemplateView):
    template_name = "blog/contact.html"

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'POST':
            data = request.POST.copy()
            name = data.get('name')
            email = data.get('email')
            phone_number = data.get('phone')
            message = data.get('message')
            text = f'from : {email} \nmessage : {message}'
            email_object = EmailMessage((name, phone_number), text,
                                        to=[settings.EMAIL_HOST_USER])
            print(email_object.send())
            return render(request, 'blog/contact_success.html')
        return render(request, 'blog/contact.html')


from tagging.views import TaggedObjectList


class PostTaggedObjectList(TaggedObjectList):
    model = Post
    allow_empty = True
    template_name = 'post/post_list.html'

#
# from django.views.generic import TemplateView
#
#
# class TagList(TemplateView):
#     template_name = 'post/tag_list.html'

blog/templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
{% endblock %}

{% block content %}
<!-- Page Header -->
<header class="masthead" style="background-image: url({% static 'blog/img/about-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="page-heading">
                    <h1>About JH</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <p>패스트 캠퍼스에서 Web Programming School 과정을 듣고 있습니다.</p>
            <p>Python과 Django를 이용한 backend-side를 공부하고 있습니다.</p><br>
        </div>
    </div>
    <div id="map" style="width: 300; height: 300px; position: relative; overflow: hidden;">
        <div class="buttons" style="position: absolute; z-index:1000;">
            <input id="to-sungsu" type="button" value="FastCampus - 성수" class="btn btn-primary btn-sm"><br>
            <!--<input id="to-gangnam" type="button" value="FastCampus - 강남" class="btn btn-secondary btn-sm">-->
        </div>
    </div>
</div>
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://github.com/navill">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; JH Website 2019</p>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

{% block extra_script %}
<script>
<!--맵 객체 생성-->
var map = new naver.maps.Map(document.getElementById('map'), {
center: new naver.maps.LatLng(37.545006, 127.057081),
zoom: 12
});

var gangnam = new naver.maps.LatLng(37.495492, 127.029336),
sungsu = new naver.maps.LatLng(37.545006, 127.057081);
var marker = new naver.maps.Marker({position: sungsu, map: map});

var contentString = [
        '<div class="iw_inner">',
        '   <h3>FastCampus-성수</h3>',
        '   <p>서울특별시 성동구 성수이로 113 / 제강빌딩 8층<br />',
        '       <a href="https://www.fastcampus.co.kr" target="_blank">https://www.fastcampus.co.kr</a>',
        '   </p>',
        '</div>'
    ].join('');
var infowindow = new naver.maps.InfoWindow({
    content: contentString
});

naver.maps.Event.addListener(marker, "click", function(e) {
    if (infowindow.getMap()) {
        infowindow.close();
    } else {
        infowindow.open(map, marker);
    }
});
infowindow.open(map, marker);

</script>
{% endblock %}

blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
<p>category_list</p>
{% for object in category_object_list %}
<a href="{% url 'blog:c_list' object.id %}">{{object.name}}</a>
<!--/ {{object.title}} / {{object.text|safe}} <br>-->
{% endfor %}

{% endblock %}

blog/templates/blog/contact.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
Clean Blog - Start Bootstrap Theme
{% endblock %}
{% block content %}
  <!--block content-->

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({% static 'blog/img/contact-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form method="post" name="sentMessage" id="contactForm" novalidate>
          {% csrf_token %}
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" name="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" name="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" name="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" name="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://github.com/navill">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; JH Website 2019</p>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

blog/templates/blog/contact_success.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
Clean Blog - Start Bootstrap Theme
{% endblock %}
{% block content %}
  <!--block content-->

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/blog/img/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Thank You for Your Interest in My Blog</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto" style="text-align:center;">
        <a href="/" class="btn btn-primary">Home</a>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://github.com/navill">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; JH Website 2019</p>
        </div>
      </div>
    </div>
  </footer>
{% endblock %}

blog/templates/blog/post_create.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.media}} {# field나 form에 설정된 css, js 파일 목록을 출력 #}
    {{form.as_p}} {# form.as_p : form tag 출력 #}
    <input type="submit" value="Write">
</form>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    delete?
    <input type="submit" value="delete">
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
{% endblock %}

{% block content %}
{% load tagging_tags %}

<!-- Page Header -->
<header class="masthead" style="background-image: url({% static 'blog/img/post-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{object.title}}</h1>
                    <h2 class="subheading">
                        {% tags_for_object object as tags %}
                        {% if tags %}
                        {% for tag in tags %}
                        <a href="{% url 'blog:post_taggedlist' tag.name %}" style="color:#fff">#{{tag.name}} </a>
                        {% endfor %}
                        {% else %}Empty Tag{% endif %}</h2>
                    <span class="meta">Posted by JH
                    <a href="#">{{object.author}}</a> at
                    {{object.created}}</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-md-12 mx-auto">
                {{object.text|safe}}
            </div>
        </div>
    </div>
</article>
<hr>

<!--<a href="{% url 'blog:update' object.id %}">수정</a>-->
<!--<a href="{% url 'blog:delete' object.id %}">삭제</a>-->
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
{% endblock %}

{% block content %}
<!-- Page Header -->
<!--TODO : list page의 주소를 확인할 수 있지만 detail에 접속할 경우 '/detail/13/static/blog/img/home-bg.jpg'를 인식하지 못하는 문제-->
<header class="masthead" style="background-image: url({% static 'blog/img/home-bg.jpg' %})">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>JH Blog</h1>
                    <span class="subheading">A Blog applied with BootStrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
{% load tagging_tags %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for object in object_list %}
            <div class="post-preview">
                <a href="{% url 'blog:detail' object.id %}">
                    <h2 class="post-title">
                        {{object.title}}
                    </h2>
                    <h3 class="post-tag">
                        {% tags_for_object object as tags %}
                            {% if tags %}
                                {% for tag in tags %}
                                    <a href="{% url 'blog:post_taggedlist' tag.name %}" style="color:#a3b4c3">#{{tag.name}} </a>
                                    <!--리스트 페이지의 태그 네임 출력-->
                                {% endfor %}
                            {% else %}
                            Empty Tag
                            {% endif %}
                    </h3>
                </a>
                <p class="post-meta">Posted by {{object.author.username}}
                    at {{object.updated}}
                </p>
            </div>
            <hr>
            {% endfor %}

            <!-- Pager -->
            <!--<div class="clearfix">-->
            <!--<a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>-->
            <!--</div>-->
            <div class="pagination">
                {% if object_list.has_previous %}
                <a class="pagination-action" href="?page=1">
                    <i class="fas fa-angle-double-left" aria-hidden="false"> </i>
                </a>
                <a class="pagination-action" href="?page={{ object_list.previous_page_number }}">
                    <i class="fas fa-angle-left" aria-hidden="true"> </i>
                </a>
                {% endif %}
                {% for num in object_list.paginator.page_range %}
                {% if object_list.number == num %}
                <span class="pagination-number pagination-current"> {{ num }} </span>
                {% elif num > object_list.number|add:'-3' and num < object_list.number|add:'3' %}
                <a class="pagination-number" href="?page={{ num }}"> {{ num }} </a>
                {% endif %}
                {% endfor %}
                {% if object_list.has_next %}
                <a class="pagination-action" href="?page={{object_list.next_page_number}}">
                    <i class="fas fa-angle-right" aria-hidden="true"></i>
                </a>
                <a class="pagination-action" href="?page={{object_list.paginator.num_pages}}">
                    <i class="fas fa-angle-double-right" aria-hidden="true"></i>
                </a>
                {% endif %}
            </div>
        </div>
    </div>

</div>

<hr>
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="수정">
</form>
{% endblock %}

blog/templates/blog/tag_list.html
<!--{% extends 'base.html' %}-->

<!--{% block title %}Tag List{% endblock %}-->

<!--{% block content %}-->

<!--{% load tagging_tags%}-->
<!--{% tag_cloud_for_model post.Post as post_tags with steps=9 min_count=1 distribution=log %}-->
    <!--{% for tag in post_tags %}-->
        <!--<a href="{% url 'blog:post_taggedlist' tag.name %}" style="font-size:{{tag.font_size}}em;">{{tag}}</a>-->
    <!--{% endfor %}-->
<!--{% endblock %}-->